apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"teste-local-cluster"},"name":"app","namespace":"mysql"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"app"}},"template":{"metadata":{"labels":{"app":"app"}},"spec":{"containers":[{"image":"quay.io/egoncalv/php-hello","name":"app"}]}}}}
  creationTimestamp: "2024-02-06T02:58:58Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: teste-local-cluster
  name: app
  namespace: mysql
  resourceVersion: "1212716"
  uid: 3e90d3bb-6877-4230-ba62-c769140bbcd1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: quay.io/egoncalv/php-hello
        imagePullPolicy: IfNotPresent
        name: app
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-02-06T03:02:31Z"
    lastUpdateTime: "2024-02-06T03:02:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-02-06T02:58:58Z"
    lastUpdateTime: "2024-02-06T03:02:31Z"
    message: ReplicaSet "app-fbfc566cf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
