apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: mysql
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"

