apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: registry.access.redhat.com/ubi8/nginx-120:1-137

